### ISSUE TITLE
Crash when disabling color output

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/Xcodeproj#267]
`xcodeproj show test.xcodeproj` will show red color for the title, so I parse fail with yaml format.

I try `xcodeproj show test.xcodeproj --no-color`, I get a crash:
```
can't modify frozen String
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/gems/xcodeproj-0.24.1/lib/xcodeproj/command/show.rb:54:in `block in run'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/gems/xcodeproj-0.24.1/lib/xcodeproj/command/show.rb:49:in `each'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/gems/xcodeproj-0.24.1/lib/xcodeproj/command/show.rb:49:in `run'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/gems/xcodeproj-0.24.1/lib/xcodeproj/command.rb:77:in `run'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/gems/xcodeproj-0.24.1/bin/xcodeproj:13:in `<top (required)>'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/bin/xcodeproj:23:in `load'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/bin/xcodeproj:23:in `<main>'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/Users/whirlwind/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

How to disable color?

**Comment by AliSoftware** [comment]
Confirmed bug with `xcodeproj 0.23.1`.
