### ISSUE TITLE
config-dump --help crashes

### ISSUE THREAD

**Issue by niklassaers** [CocoaPods/Xcodeproj#274]
```
xcodeproj config-dump --help
/Users/niklas/.rvm/gems/ruby-2.2.0/gems/xcodeproj-0.24.2/lib/xcodeproj/command/config_dump.rb:15:in `banner': undefined method `strip_heredoc' for #<String:0x007f96fb951048> (NoMethodError)
	from /Users/niklas/.rvm/gems/ruby-2.2.0/gems/xcodeproj-0.24.2/lib/xcodeproj/command.rb:19:in `message'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/gems/xcodeproj-0.24.2/lib/xcodeproj/command.rb:85:in `rescue in run'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/gems/xcodeproj-0.24.2/lib/xcodeproj/command.rb:76:in `run'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/gems/xcodeproj-0.24.2/bin/xcodeproj:13:in `<top (required)>'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/bin/xcodeproj:23:in `load'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/bin/xcodeproj:23:in `<main>'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/niklas/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Thanks @niklassaers, I've just pushed a fix!
