### ISSUE TITLE
Set build settings raise "RuntimeError - [Xcodeproj] Unrecognized object `1146614241716823128` in #tree_hash_to_path"

### ISSUE THREAD

**Issue by siuying** [CocoaPods/Xcodeproj#286]
I use xcodeproj in cocoapods post install hooks:

```
post_install do |installer|
  # Disable "Application Extension API Only" flag in pods
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = false
    end
  end
end
```

After updated to cocoapods 0.38.0.beta2 and xcodeproj 0.26.1, I got following error:

```
RuntimeError - [Xcodeproj] Unrecognized object `1146614241716823128` in #tree_hash_to_path
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:96:in `tree_hash_to_path'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:87:in `block in tree_hash_to_path'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `each_with_object'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `tree_hash_to_path'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:87:in `block in tree_hash_to_path'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `each_with_object'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:86:in `tree_hash_to_path'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:79:in `path_component_for_object'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:51:in `block (2 levels) in generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:50:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:50:in `block in generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:49:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:49:in `generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:46:in `block in generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:44:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:44:in `generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:51:in `block (2 levels) in generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:50:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:50:in `block in generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:49:in `each'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:49:in `generate_paths'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project/uuid_generator.rb:12:in `generate!'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/xcodeproj-0.26.1/lib/xcodeproj/project.rb:337:in `predictabilize_uuids'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:647:in `block in write_pod_project'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:642:in `write_pod_project'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:155:in `block in generate_pods_project'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:149:in `generate_pods_project'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:109:in `install!'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Users/siuying/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/siuying/.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
/Users/siuying/.rvm/gems/ruby-2.1.5/bin/pod:23:in `<main>'
/Users/siuying/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/siuying/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>
```

I have a quick glance on the xcodeproj API, build_settings should still work as before?

**Comment by segiddins** [comment]
Can you share a project that reproduces this issue? Does it go away if you remove the post_install hook? (The stack trace alone isn't strictly enough for me to figure out the issue, but I think I have a clue...)

**Comment by siuying** [comment]
I created a new project to replicate this: http://cl.ly/1P3X0f0F1A0S

**Comment by stevelaw** [comment]
For what it's worth, I am getting the same error with version `0.38.0`, and is caused by this post install hook:

```
target.build_configurations.each do |config|
    if config.name == 'Development'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 0
    end
end```

**Comment by siuying** [comment]
Thanks @segiddins !
