### ISSUE TITLE
private method `open' called for Xcodeproj::Project:Class on Travis

### ISSUE THREAD

**Issue by squarefrog** [CocoaPods/Xcodeproj#319]
I've submitted a [Pull Request](https://github.com/KrauseFx/fastlane/pull/702) to [Fastlane](https://github.com/KrauseFx/fastlane/pull/702) which uses `Xcodeproj` in the spec to verify changes to an `xcodeproj`. The spec which uses it is currently failing on [Travis CI](https://travis-ci.org/KrauseFx/fastlane/jobs/85698272), but passes locally. The full error is:

```
2) Fastlane Fastlane::FastFile Update App Identifier Integration should raise an exception when PRODUCT_BUNDLE_IDENTIFIER in info plist but not project
   Failure/Error: project = Xcodeproj::Project.open(xcodeproj)
   NoMethodError:
     private method `open' called for Xcodeproj::Project:Class
   # ./spec/actions_specs/update_app_identifier_spec.rb:67:in `block (4 levels) in <top (required)>'
```

Additionally, I receive another error related to finding a library

```
1) Fastlane Fastlane::FastFile Update App Identifier Integration updates the xcode project when product bundle identifier in use
     Failure/Error: end").runner.execute(:test)
     Fiddle::DLError:
       /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation: cannot open shared object file: No such file or directory
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:282:in `image'
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:318:in `extern'
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:327:in `<module:CoreFoundation>'
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:158:in `<top (required)>'
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:7:in `require'
     # /home/travis/.rvm/gems/ruby-2.2.2/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:7:in `<top (required)>'
     # ./lib/fastlane/actions/update_app_identifier.rb:22:in `run'
     # ./lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
     # ./lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
     # ./lib/fastlane/runner.rb:128:in `block in execute_action'
     # ./lib/fastlane/runner.rb:127:in `chdir'
     # ./lib/fastlane/runner.rb:127:in `execute_action'
     # ./lib/fastlane/fast_file.rb:149:in `method_missing'
     # (eval):2:in `block in parsing_binding'
     # ./lib/fastlane/lane.rb:36:in `call'
     # ./lib/fastlane/lane.rb:36:in `call'
     # ./lib/fastlane/runner.rb:51:in `block in execute'
     # ./lib/fastlane/runner.rb:46:in `chdir'
     # ./lib/fastlane/runner.rb:46:in `execute'
     # ./spec/actions_specs/update_app_identifier_spec.rb:54:in `block (4 levels) in <top (required)>'
```

I have very limited experience with Ruby so would appreciate any advice on how to solve these errors.

**Comment by neonichu** [comment]
The Travis job runs on Linux, Xcodeproj doesn't work on Linux.

**Comment by squarefrog** [comment]
Of course it doesn't - I didn't see that! Thanks @neonichu !
