### ISSUE TITLE
Error running pod install for Qt application (iOS)

### ISSUE THREAD

**Issue by marcosiciliano** [CocoaPods/Xcodeproj#347]
Hi,

i try to use 'Braintree' in my Qt iOS app.

When running 

pod install

i get the following error:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 069d75d79a146b0ab057c083cf99aa651833df70
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
pod 'Braintree'
```

### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:308:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:277:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:274:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:274:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:195:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:32:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:656:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Greetings
Nando

**Comment by segiddins** [comment]
Can you share the Xcode project that led to this exception being raised? It's possible there's a new attribute in Xcode 7.2, though I doubt it.

**Comment by marcosiciliano** [comment]
Which file do you mean ?

project.pbxproj  ?

**Comment by orta** [comment]
Yeah, that should do it

**Comment by marcosiciliano** [comment]
[project.pbxproj.txt](https://github.com/CocoaPods/Xcodeproj/files/72822/project.pbxproj.txt)

i renamed it to .txt

thank you for your help....

**Comment by segiddins** [comment]
Awesome, thanks!

**Comment by segiddins** [comment]
Hm, I'm not seeing `refType` anywhere in that file...

**Comment by marcosiciliano** [comment]
Sorry i think it was the wrong file. I will Check it tomorrow and send the correct file.

**Comment by segiddins** [comment]
:+1:

**Comment by marcosiciliano** [comment]
Hi,
here it is. Now with refType stuff inside.

[project.pbxproj.txt](https://github.com/CocoaPods/Xcodeproj/files/73371/project.pbxproj.txt)

Greetings

**Comment by marcosiciliano** [comment]
Hi,
could you find something?

Greetings from frankfurt germany :)

Marco

**Comment by orta** [comment]
Thanks @marcosiciliano - looks like this exists on quite a [few projects](https://github.com/search?langOverride=&q=reftype+xcodeproj&repo=&start_value=1&type=Code) - I think we might need to add this to the xcodeproj gem

**Comment by orta** [comment]
FWIW: This was raised last year https://github.com/CocoaPods/Xcodeproj/issues/122 - and I think we opted to not support it as Xcode doesn't anymore.

**Comment by orta** [comment]
and https://github.com/CocoaPods/Xcodeproj/issues/314

**Comment by marcosiciliano** [comment]
hi orta :)

thanks for your reply. 
i am sorry, but i am absolutely new to cocoa pods. 
so what do i have to do to get it working?
i just want to use braintree in my project...
Greetings
Marco

**Comment by kafeg** [comment]
Hi, marcosiciliano.

I found workaround and example of use Qt with CocoaPods at this repo https://github.com/GMaxera/QtFabric.
