### ISSUE TITLE
Unsupported attribute: {"outputFilesCompilerFlags"=>["-w", ""]}

### ISSUE THREAD

**Issue by silyevsk** [CocoaPods/Xcodeproj#362]
A project with a build rule which has an output with compile flag causes the following exception:

```
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:308:in `configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"outputFilesCompilerFlags"=>["-w", ""]} for the 'PBXBuildRule' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:250:in `new_from_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:195:in `initialize_from_file'
```

**Comment by segiddins** [comment]
Can you please share the project so we can investigate? Thanks!

**Comment by silyevsk** [comment]
Sure, here's a sample project:
[CustomRuleWithCustomArgument.zip](https://github.com/CocoaPods/Xcodeproj/files/171129/CustomRuleWithCustomArgument.zip)

**Comment by segiddins** [comment]
I have this working locally, will try and push up a PR in the next couple of days
