### ISSUE TITLE
Project.open crashes if path includes +

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/Xcodeproj#369]
This command crashes if the path includes a plus symbol (+).

```
@project = Xcodeproj::Project.open(@xcodeproj_path)
```

The offending code entrance:

```
https://github.com/CocoaPods/Xcodeproj/blob/1.0.0.rc.1/lib/xcodeproj/project.rb#L102
```

The deepest stack track:

```
https://github.com/CocoaPods/Xcodeproj/blob/1.0.0.rc.1/lib/xcodeproj/plist/ffi/core_foundation.rb#L73
```

The common use case is when creating a project which is a category, like NSString+AwesomeFunction. Such names customarily includes plus signs.

Test case:

```
fulldecent@FDMBA2015 ~/Desktop> pod lib create --template-url="git://github.com/fulldecent/pod-template" NSString+UsefulExtension
Cloning `git://github.com/fulldecent/pod-template` into `NSString+UsefulExtension`.
Configuring NSString+UsefulExtension template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > 
swift
Would you like to include a demo application with your library? [ Yes / No ]
 > 
yes
Which testing frameworks will you use? [ Quick / None ]
 > 
quick
Would you like to do view based testing? [ Yes / No ]
 > 
yes2016-05-01 18:39:52.927 ruby[73302:5006873] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 29. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/plist/ffi/core_foundation.rb:271:in `ptr': uninitialized constant CoreFoundation (NameError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/plist/ffi/core_foundation.rb:73:in `RubyHashPropertyListRead'
    from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/plist/ffi.rb:54:in `read_from_path'
    from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/plist.rb:22:in `read_from_path'
    from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
    from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.rc.1/lib/xcodeproj/project.rb:102:in `open'
    from /Users/fulldecent/Desktop/NSString+UsefulExtension/setup/ProjectManipulator.rb:30:in `run'
    from /Users/fulldecent/Desktop/NSString+UsefulExtension/setup/ConfigureSwift.rb:49:in `perform'
    from /Users/fulldecent/Desktop/NSString+UsefulExtension/setup/ConfigureSwift.rb:7:in `perform'
    from /Users/fulldecent/Desktop/NSString+UsefulExtension/setup/TemplateConfigurator.rb:76:in `run'
    from ./configure:9:in `<main>'

To learn more about the template see `git://github.com/fulldecent/pod-template`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```

**Comment by fulldecent** [comment]
@fabiopelosin @alloy Would a PR that fixes this be in scope to be merged?

**Comment by segiddins** [comment]
This should work in the most recent version given we no longer use CF at all

**Comment by fulldecent** [comment]
Confirmed, thank you. Closing.
