### ISSUE TITLE
NoMethodError: undefined method `red'

### ISSUE THREAD

**Issue by vincentisambart** [CocoaPods/Xcodeproj#374]
``` ruby
require "xcodeproj"
begin
  Xcodeproj::Plist.read_from_path("not-existing-file")
rescue => e
  p e.message
end
```

Running the code above give the following error:

```
[...]/gems/xcodeproj-1.0.0/lib/xcodeproj.rb:11:in `message': undefined method `red' for "[!] The plist file at path `not-existing-file` doesn't exist.\n":String (NoMethodError)
    from test.rb:5:in `rescue in <main>'
    from test.rb:2:in `<main>'
```

`.red` is used in `lib/xcodeproj.rb` even though `colored` is only `require`d when Xcode::Command is autoloaded.

**Comment by segiddins** [comment]
Looks like we should just `require 'colored'` in `xcodeproj.rb` then?

**Comment by vincentisambart** [comment]
That should do the trick 😄
