### ISSUE TITLE
crash under Xcode 8 beta 6 and Sierra PB 5

### ISSUE THREAD

**Issue by SpiraMira** [CocoaPods/Xcodeproj#403]
Am receiving this error after my project was built under Xcode 8 beta 6.  
Looks like this new version of Xcode has introduced some new attributes...
The project is being generated by CMake -GXcode.  Not sure if that makes any difference.

`/Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["334FFEFC836C4657AB4364F6", "06940D20BBA64B85AADC5514", "B19BE37AAEED49E5AAC3B7BC", "E12C544D5FF5410E9B3D0057"]} for the 'PBXProject' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
       	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
       	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:202:in `initialize_from_file'
       	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:102:in `open'
       	from krita_fix_targets.rb:49:in `<main>'`

My ruby program runs when opening an older version (Xcode 8 beta 5 based) of my project (also generated by CMake 3.6)

Any help is greatly appreciated.  Can help debug this on my side if necessary.

Regards, Patrice

**Comment by segiddins** [comment]
Can you share the project? Thanks!

**Comment by SpiraMira** [comment]
Sure here goes...

[krita.xcodeproj.zip](https://github.com/CocoaPods/Xcodeproj/files/425704/krita.xcodeproj.zip)

I hack it to fix cmake anomalies and target stuff with programs like this...pretty basic ruby (I'm not an expert...just picked it up yesterday ;-)

btw, great tool and project...keep it going...

[ruby-scripts.tar.gz](https://github.com/CocoaPods/Xcodeproj/files/425719/ruby-scripts.tar.gz)

Regards, Patrice

**Comment by segiddins** [comment]
Thanks!

**Comment by SpiraMira** [comment]
Hi just curious if you were able to confirm that it's an issue with Xcode 8 or not.

**Comment by segiddins** [comment]
I don't know if anyone's had a chance to look into it yet

**Comment by SpiraMira** [comment]
I know everyone's pressed for time. I'm willing to look into this, if an xcodeproject expert developer can point me in the right direction...to summarize: it seems like new attributes were introduced in Xcode beta 6. They break my rather simple script to alter my cmake generated project. Worked fine in beta 5.

Regards Patrice
