### ISSUE TITLE
Xcode 8 new object version

### ISSUE THREAD

**Issue by puttin** [CocoaPods/Xcodeproj#412]
Xcode 8 has a new object version

<details>
<summary>CocoaPods output</summary>
### Command

```
/Users/****/.rbenv/versions/2.2.1/bin/pod init
```

### Report

* What did you do?
`pod init`

* What did you expect to happen?
Podfile generated

* What happened instead?
error

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8S201h)
         Git : git version 2.9.3
Ruby lib dir : /Users/Puttin/.rbenv/versions/2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ acf635b2ed298a4154b1b783f5461f80aabba24d
```

### Plugins

```
cocoapods-deintegrate    : 1.0.0
cocoapods-no-dev-schemes : 1.0.1
cocoapods-plugins        : 1.0.0
cocoapods-search         : 1.0.0
cocoapods-stats          : 1.0.0
cocoapods-trunk          : 1.0.0
cocoapods-try            : 1.1.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:102:in `open'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:333:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/****/.rbenv/versions/2.2.1/bin/pod:23:in `load'
/Users/****/.rbenv/versions/2.2.1/bin/pod:23:in `<main>'
```

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
</detail>

**Comment by orta** [comment]
Have you tried with the betas? I think https://github.com/CocoaPods/Xcodeproj/pull/389 fixed this

**Comment by puttin** [comment]
Just tried the beta version, and it doesn't work either.

<details>
<summary>CocoaPods 1.1.0.beta.2 output</summary>
### Command

```
/Users/****/.rbenv/versions/2.2.1/bin/pod init
```

### Report

* What did you do?
`bundle exec pod init`

* What did you expect to happen?
Podfile generated

* What happened instead?
error

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8S201h)
         Git : git version 2.10.0
Ruby lib dir : /Users/****/.rbenv/versions/2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ acf635b2ed298a4154b1b783f5461f80aabba24d
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-1.3.0/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-1.3.0/lib/xcodeproj/project.rb:102:in `open'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:333:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command.rb:50:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.beta.2/bin/pod:55:in `<top (required)>'
/Users/****/.rbenv/versions/2.2.1/bin/pod:23:in `load'
/Users/****/.rbenv/versions/2.2.1/bin/pod:23:in `<top (required)>'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/****/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/****/.rbenv/versions/2.2.1/bin/bundle:23:in `load'
/Users/****/.rbenv/versions/2.2.1/bin/bundle:23:in `<main>'
```
</details>

<details>
<summary>My Gemfile.lock</summary>

```
GEM
  remote: https://gems.ruby-china.org/
  specs:
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    claide (1.0.0)
    cocoapods (1.1.0.beta.2)
      activesupport (>= 4.0.2, < 5)
      claide (>= 1.0.0, < 2.0)
      cocoapods-core (= 1.1.0.beta.2)
      cocoapods-deintegrate (>= 1.0.1, < 2.0)
      cocoapods-downloader (>= 1.1.1, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-stats (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.0.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored (~> 1.2)
      escape (~> 0.0.4)
      fourflusher (~> 1.0.1)
      gh_inspector (~> 1.0)
      molinillo (~> 0.5.0)
      nap (~> 1.0)
      xcodeproj (>= 1.3.0, < 2.0)
    cocoapods-core (1.1.0.beta.2)
      activesupport (>= 4.0.2, < 5)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
    cocoapods-deintegrate (1.0.1)
    cocoapods-downloader (1.1.1)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.0)
    cocoapods-stats (1.0.0)
    cocoapods-trunk (1.0.0)
      nap (>= 0.8, < 2.0)
      netrc (= 0.7.8)
    cocoapods-try (1.1.0)
    colored (1.2)
    escape (0.0.4)
    fourflusher (1.0.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.0.2)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.9.0)
    molinillo (0.5.0)
    nap (1.1.0)
    netrc (0.7.8)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    xcodeproj (1.3.0)
      activesupport (>= 3)
      claide (>= 1.0.0, < 2.0)
      colored (~> 1.2)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods (= 1.1.0.beta.2)

BUNDLED WITH
   1.12.5
```

</details>

**Comment by DanToml** [comment]
@puttin which Xcode Beta are you running?

**Comment by puttin** [comment]
@DanToml As u see in the log: Version 8.0 beta 6 (8S201h)

**Comment by neonichu** [comment]
This is right, however it seems like only some of the templates will use the new object version, but one can still manually select it:

<img width="186" alt="screen shot 2016-09-06 at 19 49 24" src="https://cloud.githubusercontent.com/assets/118992/18294932/13db666a-746b-11e6-94e2-a144768c01be.png">

**Comment by puttin** [comment]
Yes the Xcode 8.0-compatible is using version 48. And the diff is only the `48`

I don't like to use old Xcode version, so I always prefer new format.
