### ISSUE TITLE
[Xcodeproj] Consistency issue: no parent for object `Main Group`: ``

### ISSUE THREAD

**Issue by tirodkar** [CocoaPods/Xcodeproj#416]
This issue is seen only in 1.3.1. On setting the bundle version to 1.3.0., the issue doesn't come up.

Description: If you clone and run the rspec tests for the [EarlGrey gem](https://github.com/google/EarlGrey/tree/master/gem) then you will notice a trace containing:
```
  1) configure_earlgrey configures for carthage
     Failure/Error: test_target_group.new_reference(file)
     RuntimeError:
       [Xcodeproj] Consistency issue: no parent for object `Main Group`: ``
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:18:in `parent'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:118:in `source_tree_real_path'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:187:in `set_path_with_source_tree'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/file_references_factory.rb:102:in `new_file_reference'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/file_references_factory.rb:31:in `new_reference'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/group.rb:222:in `new_reference'
     # ./lib/earlgrey/configure_earlgrey.rb:379:in `block in copy_swift_files'
     # ./lib/earlgrey/configure_earlgrey.rb:377:in `each'
     # ./lib/earlgrey/configure_earlgrey.rb:377:in `copy_swift_files'
     # ./lib/earlgrey/configure_earlgrey.rb:123:in `configure_for_earlgrey'
     # ./lib/earlgrey/cli.rb:49:in `install'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
     # /Users/travis/.rvm/gems/ruby-2.2.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
     # ./spec/spec_helper.rb:80:in `block (2 levels) in diff_project'
     # ./spec/spec_helper.rb:72:in `chdir'
     # ./spec/spec_helper.rb:72:in `block in diff_project'
     # ./spec/spec_helper.rb:69:in `diff_project'
     # ./spec/configure_earlgrey_spec.rb:20:in `block (2 levels) in <top (required)>'
```

The issue is caused on [this line](https://github.com/google/EarlGrey/blob/master/gem/lib/earlgrey/configure_earlgrey.rb#L271):

```
      framework_path = if carthage
                         '${SRCROOT}/Carthage/Build/iOS/EarlGrey.framework'
                       else
                         '${SRCROOT}/Pods/EarlGrey/EarlGrey/EarlGrey.framework'
                       end

      framework_ref = user_project.products_group.files.find { |f| f.path == framework_path }
```

We basically obtain the path to our EarlGrey framework from the project's directory and then add it as a Copy Files framework. Has this been modified by any chance?

**Comment by tirodkar** [comment]
Removing the `product_ref_group` change made [here](https://github.com/CocoaPods/Xcodeproj/pull/410/files#diff-ccced35716e27e4d7259742d116d2643R219) fixes this issue. I noticed that the products_group was already populated for my project before the setter was added. Maybe we need to have a nil check around it?

**Comment by tirodkar** [comment]
Closing this. This is caused because of the Products Group in the xcodeproj being deleted. Thanks.

**Comment by maciejtrybilo** [comment]
Would you consider pushing a release with the fix soon? This issue is causing a lot of grief https://github.com/CocoaPods/CocoaPods/issues/5847 For people moving to Swift 3 downgrading to 1.3.0 doesn't help.
