### ISSUE TITLE
Failure when reading plist

### ISSUE THREAD

**Issue by vdesaintpern** [CocoaPods/Xcodeproj#435]
```
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.0/lib/nanaimo/reader.rb:61:in `initialize': uninitialized constant Nanaimo::Reader::StringScanner (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
	from /Users/vivien/laBoiteMobile/repos/mobile-apps/hooks/fix_xcode_schemes_extra.rb:3:in `<main>'
Error: Hook failed with error code 1: /Users/vivien/laBoiteMobile/repos/mobile-apps/hooks/fix_xcode_schemes_extra.rb
```

My fix_xcode_schemes_extra.rb looks like this :

```
require 'xcodeproj'
xcproj = Xcodeproj::Project.open("platforms/ios/LOCAL-Extracadabra.xcodeproj")
xcproj.recreate_user_schemes
xcproj.save
```

Reverting to 1.3.3 fixed the issue. Please have a look, I wasted 2h investigating the issue : it looks like some sort of import is missing (I don't know ruby)

**Comment by segiddins** [comment]
I'm fixing this right now, sorry!

**Comment by segiddins** [comment]
If you run `gem install nanaimo` now, it should fix things.
