### ISSUE TITLE
[Xcodeproj] Consistency issue: no parent for object `libz.1.dylib`: `FrameworksBuildPhase`, `FrameworksBuildPhase`

### ISSUE THREAD

**Issue by dnstevenson1** [CocoaPods/Xcodeproj#439]
Just updated to Cocoapods 1.1.1, Xcode 8.1, and Xcodeproj 1.4.0.

We have a ruby script that duplicates an existing target in the project. This has been working for months on Cocoapods 0.39 & Xcode 8. 

The ruby code is like this:
```
new_target = source_target.dup
project.targets << new_target
project.save
```

Now when we try out the code we get the following error. The resulting project.pbxproj is 0 bytes.

```
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:18:in `parent': [Xcodeproj] Consistency issue: no parent for object `libz.1.dylib`: `FrameworksBuildPhase`, `FrameworksBuildPhase` (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project/object/build_file.rb:63:in `ascii_plist_annotation'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:286:in `block in to_ascii_plist'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:285:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:285:in `to_ascii_plist'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `block in save'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `open'
	from /usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `save'
```

I have read similar consistency issues, but they seem related to installing pods or with Xcodeproj 1.3. My pods install fine; the project builds & runs fine in Xcode 8.1

**Comment by segiddins** [comment]
Can you please share whatever project and code is necessary to reproduce the issue? Thanks!

**Comment by dnstevenson1** [comment]
I figured you'd need a sample project to be of much help :( Unfortunately it's a commercial app and I can't get it to you. I've tried setting up a new Xcode project and reproducing it, but so far I'm out of luck reproducing it on a new project. 

I removed the libz.1.dylib from the Frameworks list and re-added it and the error went on to the next framework in the list. So my guess is the project file has been corrupted somehow in the last few years it's been around.

I can confirm that by going back to xcodeproj v1.3.3 we can dup the targets again. I'll keep tracing through the v1.4.0 code and see if I can determine better what is causing the failure.

**Comment by muyanbiao** [comment]
I came up with below same error:
"RuntimeError: [Xcodeproj] Consistency issue: no parent for object `UserNotifications.framework`: `FrameworksBuildPhase`, `FrameworksBuildPhase`"
And I removed the `UserNotifications.framework` from the Frameworks list and re-added it, and the error disappeared. Just like @dnstevenson1's case.
Could please check what's the key problem here?

Xcodeproj: 1.19.0

**Comment by thesanketkale** [comment]
+1 on this. Getting the same error but in my case, it's a different framework. I am building my unity project from version 2022.1.8f1 and getting the below error on pod install:
[Xcodeproj] Consistency issue: no parent for object `NatDevice.framework`: `Embed Frameworks`, `FrameworksBuildPhase` (RuntimeError)

Mine is a commercial app as well, hence won't be able to share the project, sorry. 

Removing and re-adding the framework in the Xcode project and then doing pod install works, but it's a pain to do things manually after building a unity app.

Is there any better solution/workaround for this? Thanks.

**Comment by thesanketkale** [comment]
I have created a demo project which could reproduce this bug. I am sharing the Xcode project and Unity project both for your reference. The Xcode project in my case is auto-generated by building the Unity project for the iOS platform.

Pod install error demo Xcode project:
https://drive.google.com/file/d/1jcPwPJWY4M41qG2D62wpPdRHvMsTz4CW/view?usp=sharing

Pod install error demo Unity project:
https://drive.google.com/file/d/1ohBa56qZrgMLq5r7Z_EP8i2yx0yzba_3/view?usp=sharing

The project is a simple demo that uses Firebase and NatDevice frameworks together and fails to do pod install in the Xcode project due to Consistency issue.

Hope to get an official solution for this.

**Comment by mspacemedia** [comment]
Same issue `RuntimeError - [Xcodeproj] Consistency issue: no parent for object 'libiPhone-lib.dylib': 'FrameworksBuildPhase', 'Copy Shared Libraries'
` building in 2022.1.10f1 today…

**Comment by Joakim432710** [comment]
+1 Same issue,
[Xcodeproj] Consistency issue: no parent for object `NatMLHub.framework`: `Embed Frameworks`, `FrameworksBuildPhase` (RuntimeError)
