### ISSUE TITLE
Error reading Cordova generated project

### ISSUE THREAD

**Issue by wpilon** [CocoaPods/Xcodeproj#444]
Hi

xcodeproj generate error on parsing Cordova generated projet.
The problem seems to be the dash caracter inside paths.

Result of xcodeproj show : 

```
/Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:277:in `raise_parser_error': [!] Dictionary missing ';' after key-value pair for "path", found "-" (Nanaimo::Reader::ParseError)
  #  -------------------------------------------
  #             302D95EF14D2391D003F00A1 /* MainViewController.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = MainViewController.m; sourceTree = "<group>"; };
  #             302D95F014D2391D003F00A1 /* MainViewController.xib */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = file.xib; path = MainViewController.xib; sourceTree = "<group>"; };
70>             3047A50F1AB8059700498E2A /* build-debug.xcconfig */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xcconfig; name = "build-debug.xcconfig"; path = cordova/build-debug.xcconfig; sourceTree = SOURCE_ROOT; };
                                                                                                                                                                                              ^
  #             3047A5101AB8059700498E2A /* build-release.xcconfig */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xcconfig; name = "build-release.xcconfig"; path = cordova/build-release.xcconfig; sourceTree = SOURCE_ROOT; };
  #             3047A5111AB8059700498E2A /* build.xcconfig */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xcconfig; name = build.xcconfig; path = cordova/build.xcconfig; sourceTree = SOURCE_ROOT; };
  #  -------------------------------------------
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:191:in `parse_dictionary'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:185:in `parse_dictionary'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:185:in `parse_dictionary'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:99:in `parse!'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/lib/xcodeproj/command.rb:59:in `xcodeproj'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/lib/xcodeproj/command/show.rb:46:in `run'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/gems/xcodeproj-1.4.1/bin/xcodeproj:10:in `<top (required)>'
        from /Users/jenkins/.rvm/rubies/ruby-2.3.0/bin/xcodeproj:23:in `load'
        from /Users/jenkins/.rvm/rubies/ruby-2.3.0/bin/xcodeproj:23:in `<main>'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
        from /Users/jenkins/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
`gem install nanaimo:0.2.2`

**Comment by wpilon** [comment]
Well done.
Thxs
