### ISSUE TITLE
Xcodeproj doesn't know about the following attributes {"fileEncoding"=>"4"} for the 'PBXGroup' isa.

### ISSUE THREAD

**Issue by sarnau** [CocoaPods/Xcodeproj#500]
This seems to occur since Xcode 8.0.

/usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] Xcodeproj doesn't know about the following attributes {"fileEncoding"=>"4"} for the 'PBXGroup' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:287:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/project.rb:102:in `open'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/command.rb:59:in `xcodeproj'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/lib/xcodeproj/command/show.rb:46:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.0/bin/xcodeproj:10:in `<top (required)>'
	from /usr/local/bin/xcodeproj:22:in `load'
	from /usr/local/bin/xcodeproj:22:in `<main>'

**Comment by segiddins** [comment]
Can you please attach a project that raises the error? Thanks!

**Comment by sarnau** [comment]
Here we go. I removed most of the stuff from the project to keep it simple. If I remove more the issue disappears.

[Test.xcodeproj.zip](https://github.com/CocoaPods/Xcodeproj/files/1133319/Test.xcodeproj.zip)
