### ISSUE TITLE
SystemStackError after MacOS & Xcode upgrade

### ISSUE THREAD

**Issue by dthuering** [CocoaPods/Xcodeproj#511]
Hi,

today I suddenly got the following error message when running fastlane in the gym part.
Only changed MacOS to HighSierra and use XCode 9 now. 

```
/Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:135:in `match_variable': stack level too deep (SystemStackError)
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:122:in `resolve_variable_substitution'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:87:in `resolve_build_setting'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:128:in `resolve_variable_substitution'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:131:in `resolve_variable_substitution'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:87:in `resolve_build_setting'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:128:in `resolve_variable_substitution'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:131:in `resolve_variable_substitution'
	from /Users/danny/.rvm/gems/ruby-2.4.2/gems/xcodeproj-1.5.2/lib/xcodeproj/project/object/build_configuration.rb:87:in `resolve_build_setting'
	 ... 8929 levels...
	from /Users/danny/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
	from /Users/danny/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<main>'
	from /Users/danny/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/danny/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dgyesbreghs** [comment]
+1

**Comment by Ruenzuo** [comment]
Can you share a project where we can reproduce this?

**Comment by dthuering** [comment]
It is a private customer project. But I will try to reproduce.

**Comment by saeros** [comment]
Coming here from https://github.com/fastlane/fastlane/issues/10500#issuecomment-338161113.

Using `gem 'xcodeproj', '1.5.1'` worked for me.

**Comment by blender** [comment]
Same here, xcodeproj 1.5.1 work fine. Maybe a `git bisect` can help identifying the change the causes the problem?

**Comment by Ruenzuo** [comment]
It's very likely that this is the problem: https://github.com/CocoaPods/Xcodeproj/pull/501, but it would be really helpful to have a sample project here. 

It's either the `SDKROOT` or `PRODUCT_BUNDLE_IDENTIFIER` build setting that is causing this, [according to the usage](https://github.com/fastlane/fastlane/search?utf8=✓&q=resolve_build_setting&type=), but I'm not sure what kind of setup causes the method to recurse infinitely.

**Comment by blender** [comment]
@Ruenzuo if you can share a "quick guide to debugging" I'd be glad to help. I can't share the project unfortunately.

**Comment by Ruenzuo** [comment]
@blender can you share how you set up both build settings? Like: target value, project value and any xcconfig file that might be configured to either project or target build settings.

Alternatively, fastlane has some really good docs on how to get started with Ruby debugging: https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md#debug-using-pry

**Comment by blender** [comment]
We use fastlane's https://docs.fastlane.tools/actions/update_app_identifier/#update_app_identifier

In the project:
- there is no extra xconfig
- there are 5 targets (1 ios, 4 watchOS). iOS target is Real Green, watchOS targets are all named "Real Watch", "Real Watch (Complication)" and so on
- project format is for some reason Xcode3.2 compatible (I'm getting suspicious here)

**Comment by dthuering** [comment]
We use a .xcconfig file to set PRODUCT_BUNDLE_IDENTIFIER. 
This file is including then the .xcconfig file from CocoaPods.
Our project is quite old, so we have that XCode3.2 compatibility too. But changing it has no effect.

**Comment by Ruenzuo** [comment]
@blender thanks a lot for the information!. I think I have an idea of what's the problem here. Nowadays `CFBundleIdentifier` is defined as `$(PRODUCT_BUNDLE_IDENTIFIER)` in the App's Info.plist and fastlane is querying for that, but some projects might still use the old style (setting the value directly in the Info.plist) and don't actually have a `$(PRODUCT_BUNDLE_IDENTIFIER)` build setting.

In any case, `Xcodeproj` shouldn't crash trying to resolve a build setting that isn't defined in the project.

I'll try to reproduce this today and create a branch you can try later.

**Comment by Ruenzuo** [comment]
@blender didn't have luck so far. Any chance you can show me what do you get from: 

```
cat path/to/project.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER
```

**Comment by dthuering** [comment]
```
PRODUCT_BUNDLE_IDENTIFIER = "$(PRODUCT_BUNDLE_IDENTIFIER)";
PRODUCT_BUNDLE_IDENTIFIER = "$(PRODUCT_BUNDLE_IDENTIFIER)";
PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.bakery2-tvOS";
PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.bakery2-tvOS";
PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.bakery2-tvOSTests";
PRODUCT_BUNDLE_IDENTIFIER = "com.facebook.REACT.bakery2-tvOSTests";
```

**Comment by blender** [comment]
```
cat Real\ Green.xcodeproj/project.pbxproj | grep PRODUCT_BUNDLE_IDENTIFIER


PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen;
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen;
PRODUCT_BUNDLE_IDENTIFIER = "com.mycompany.Real-GreenTests";
PRODUCT_BUNDLE_IDENTIFIER = "com.mycompany.Real-GreenTests";
PRODUCT_BUNDLE_IDENTIFIER = "com.mycompany.Real-GreenUITests";
PRODUCT_BUNDLE_IDENTIFIER = "com.mycompany.Real-GreenUITests";
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen.watchkitapp.watchkitextension;
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen.watchkitapp.watchkitextension;
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen.watchkitapp;
PRODUCT_BUNDLE_IDENTIFIER = com.mycompany.mysubcompany.realgreen.watchkitapp;
```

**Comment by Ruenzuo** [comment]
@dthuering well that explains a lot. I didn't even know that was possible. I can reproduce the issue now I think.

@blender any chance you have something like @dthuering? Maybe before running `update_app_identifier`?

**Comment by dthuering** [comment]
We have multiple .xcconfig files that set the PRODUCT_BUNDLE_IDENTIFIER and some other settings on compile time.

**Comment by blender** [comment]
@Ruenzuo that output is before I run fastlane :(

**Comment by Ruenzuo** [comment]
@dthuering I don't understand what's the point of defining:

```
PRODUCT_BUNDLE_IDENTIFIER = "$(PRODUCT_BUNDLE_IDENTIFIER)";
```

If you set `PRODUCT_BUNDLE_IDENTIFIER` in an xcconfig file you don't have to do that to get the value, or am I missing something obvious?

**Comment by dthuering** [comment]
I see. I is overwritten by the xcconfig. When I set `PRODUCT_BUNDLE_IDENTIFIER` to a fixed value it works.

**Comment by Ruenzuo** [comment]
@dthuering Yeah, I usually leave it blank. Thank you for helping us figuring this out! Xcode works just fine with a set up like that and I guess other people also have a similar setup, so Xcodeproj should handle that.

**Comment by Ruenzuo** [comment]
@blender @dthuering could you please try the changes in this branch? https://github.com/Ruenzuo/Xcodeproj/tree/fix_infinite_recursion_resolve_build_setting

**Comment by blender** [comment]
@Ruenzuo  `Finished: SUCCESS` 🎉
