### ISSUE TITLE
Found additional characters after parsing the root plist object 

### ISSUE THREAD

**Issue by lewgun** [CocoaPods/Xcodeproj#529]
There is a project.pbxproj which can't be opened by Xcodeproj, but it's can work with XCode 9.3, the error logs as follows: 
>/Users/tgame/.rvm/gems/ruby-2.3.0@global/gems/nanaimo-
>0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] Found additional characters after >parsing the root plist object (Nanaimo::Reader::ParseError)
> #  -------------------------------------------
> #  // !$*UTF8*$!{
>2>      archiveVersion = 1;
>                       ^
> #      classes = {
> #      };
> #  -------------------------------------------
>        from /Users/tgame/.rvm/gems/ruby-2.3.0@global/gems/nanaimo->0.2.3/lib/nanaimo/reader.rb:109:in `parse!'
>        from /Users/tgame/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.2/lib/xcodeproj/plist.rb:27:in >`read_from_path'
>        from /Users/tgame/.rvm/gems/ruby-2.3.0/gems/xcodeproj->1.5.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
>
change FROM:  
  >      // !$*UTF8*$!{
TO:
  >     // !$*UTF8*$!
  >      {                        

solved it

**Comment by segiddins** [comment]
Thanks, this definitely looks like a bug in Nanaimo
