### ISSUE TITLE
undefined method `test_target_type?'

### ISSUE THREAD

**Issue by yadirhb** [CocoaPods/Xcodeproj#531]
Hi there I'm trying to recreate the user schemes for a project using the demo specification as follows: 
```
require 'xcodeproj'
xcproj = Xcodeproj::Project.open('MyApp.xcodeproj')
xcproj.recreate_user_schemes
xcproj.save
```
but I am getting this error: 

```
 ./fix_schemes.rb
/usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:812:in `block in recreate_user_schemes': undefined method `test_target_type?' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x00007fb72fcdd168> (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:809:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:809:in `recreate_user_schemes'
        from ./fix_schemes.rb:4:in `<main>'
```
I've already check inside the native_target definition and exists such method but at runtime I don't know why it is failing. I did not found any related explanation online that's why I'm reporting this issue in here. Hope can fix or explain this.

**Comment by yadirhb** [comment]
I've already checked and this fails in my project only if I add a target of type "External Build System", otherwise generates the schemes nicely. 

![image](https://user-images.githubusercontent.com/6015754/34123854-b21e9c4c-e40f-11e7-836f-c06a53cb0618.png)
