### ISSUE TITLE
Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa. (RuntimeError)

### ISSUE THREAD

**Issue by mkozjak** [CocoaPods/Xcodeproj#535]
I am generating my Qt application with [fastlane](https://fastlane.tools).
`project.pbxproj` which is created by it, obviously doesn't work okay, since it breaks at `Xcodeproj::Project.open`. Further logs below:

```
/Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] [!] Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/recreate_schemes.rb:9:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:231:in `block (2 levels) in run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/cli_tools_distributor.rb:91:in `take_off'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/bin/fastlane:20:in `<top (required)>'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
My pbxproj file: https://gist.github.com/7824a4cf3c43ec71abd50c3031fcf14f
References #500 fastlane/fastlane#11438 possibly.

**Comment by mkozjak** [comment]
Seems like I had to do `xctools build-settings clean -p` (see [xctools](https://github.com/xcodeswift/xctools)).

Then I had a different error, `Xcodeproj doesn't know about the following attributes {"buildRules"=>[]} for the 'PBXAggregateTarget' isa. (RuntimeError)` and I fixed it by removing all lines with `buildRules`.

**Comment by segiddins** [comment]
Did the project open in Xcode with those attributes present? After closing Xcode, were the attributes still there?

**Comment by mkozjak** [comment]
@segiddins: Yes, xcode does help. Nothing else does. Fixed with `awk '/buildRules/{getline;next} 1' ./uniqtv.xcodeproj/project.pbxproj > ./uniqtv.xcodeproj/project.pbxproj.new`

**Comment by segiddins** [comment]
I have a sneaking suspicion we should change that hard error to a warning, as Xcode seems to just tolerate random attributes, so we should as well.

**Comment by theoriginalgri** [comment]
Back-linking to https://bugreports.qt.io/browse/QTCREATORBUG-18352

**Comment by torarnv** [comment]
Yes, Qt may use some deprecated attributes, but Xcodeproj should definitely not hard error on them, it should ignore (and possibly warn), like Xcode does.
