### ISSUE TITLE
`pod install` does not work with xcodeproj 1.5.6 when using it from sh script from Xcode build phase.

### ISSUE THREAD

**Issue by 2energycell** [CocoaPods/Xcodeproj#558]
more info: inside build phase the `/bin/sh` changed to `/bin/bash -l` in order to get user vars

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/2energycell/.rbenv/versions/2.3.1/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
    RubyGems : 2.5.1
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/2energycell/.rbenv/versions/2.3.1/lib
Repositories : heyzap - https://github.com/Heyzap/CocoapodsSource.git @ 5848694aa5d8f16913a270ab178a15357903e1b9
               local - /Users/2energycell/CocoaPods/Local @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ fca9828ed7a167f3838ed3f1d8cc07b5ae811f3b
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
target 'IASDKClient' do
    pod 'mopub-ios-sdk', '4.17.0'
    pod 'Google-Mobile-Ads-SDK', '7.28.0'
end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:118:in `gsub'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:118:in `expand_build_setting'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:97:in `block in resolve_build_setting'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `each'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `reduce'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:96:in `resolve_build_setting'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:60:in `debug?'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/object/build_configuration.rb:68:in `type'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:227:in `block in configuration_list'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:222:in `each'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:222:in `configuration_list'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project/project_helper.rb:51:in `new_target'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.6/lib/xcodeproj/project.rb:686:in `new_target'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:48:in `add_target'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:20:in `block in install!'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:168:in `block (2 levels) in install_libraries'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:166:in `each'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:166:in `block in install_libraries'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:165:in `install_libraries'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/2energycell/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/2energycell/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/2energycell/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by paulb777** [comment]
Try verifying or removing `/Users/2energycell/CocoaPods/Local`

**Comment by Ruenzuo** [comment]
`expand_build_setting` had a bug fixed by @segiddins, but this hasn't been released yet: https://github.com/CocoaPods/Xcodeproj/commit/4088f5532bee430a5a7daaf27b3abc504e7ba4a3#diff-2ad067ae68f4a21eb76753eb41065fc7, it might be worth trying this out.

You would have to make sure that this version of `xcodeproj` is the one that your build phase command is going to pick up, or maybe using `bundle exec ...` instead of the full path to rbenv.

**Comment by 2energycell** [comment]
@Ruenzuo `xcodeproj` is not being used explicitly. Cocoapods uses it during the `pod install`. Tried `bundle exec pod install` - didn't help. In addition there is custom rb script that uses `xcodeproj` in my project at the build phase, and it works fine with any version of `xcodeproj`. So meanwhile I use `xcodeproj` 1.5.4, because I just revealed that there is the same issue with 1.5.5 as well.

**Comment by dnkoutso** [comment]
You can still update to use `xcodeproj` separately. 1.3.1 uses `> = 1.5.1` as a requirement for Xcodeproj.

https://github.com/CocoaPods/CocoaPods/blob/1.3.0/cocoapods.gemspec#L41

**Comment by dnkoutso** [comment]
You can use master version using bundler, which would be 1.5.7 but it is not yet released.

```ruby
gem 'xcodeproj', :git: "https://github.com/CocoaPods/xcodeproj"
```

then:
```
bundle 
bundle exec pod install
```

**Comment by dnkoutso** [comment]
Learn more here http://bundler.io/

**Comment by 2energycell** [comment]
Yes I use bundler, thanks!

**Comment by dnkoutso** [comment]
@2energycell if you confirm latest master works please close this issue as well.

**Comment by 2energycell** [comment]
Yes, the latest master fixed the issue.

**Comment by dnkoutso** [comment]
perfect thanks!
