### ISSUE TITLE
undefined method `to_set' in 1.5.8

### ISSUE THREAD

**Issue by ksuther** [CocoaPods/Xcodeproj#572]
e3112256a35dce2b9644bdc1bb209b330d00cad6 appears to have introduced this problem.

```
$ ruby /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb
Traceback (most recent call last):
	5: from /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<main>'
	4: from /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	3: from /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	2: from /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	1: from /Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
/Users/kent/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x00007fe45306c090> (NoMethodError)
```

I think `to_set` needs to be `to_s`.

**Comment by segiddins** [comment]
thanks for pointing this out, needs to be a `require 'set'` at the top of the file. PR incoming
