### ISSUE TITLE
Cannot save plist after modify

### ISSUE THREAD

**Issue by L3K0V** [CocoaPods/Xcodeproj#629]
Hi, 

I'm trying to save modified plist on a Rails app instance on Heroku. It looks like that the `/tmp` is not on the same filesystem as the app and the `rename` fail. It must use `move` instead. 

Is there any workaround for this?

```
[2018-12-05T14:28:02.283576 #4] ERROR -- : [ActiveJob] [ConfigureAppJob] [532ee511-06cd-4b1f-9dbb-2e1660c03244] Error performing ConfigureAppJob (Job ID: 532ee511-06cd-4b1f-9dbb-2e1660c03244) from Async(default) in 12869.72ms: Errno::EXDEV (Invalid cross-device link @ rb_file_s_rename - (/tmp/.atomos.project.pbxproj20181205-4-13jr4xy, /app/tmp/demo-apps.git/Kolibri.xcodeproj/project.pbxproj)):
2018-12-05T13:28:02.283693+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `rename'
2018-12-05T13:28:02.283695+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `block in atomic_write'
2018-12-05T13:28:02.283697+00:00 app[web.1]: /app/vendor/ruby-2.5.3/lib/ruby/2.5.0/tempfile.rb:295:in `open'
2018-12-05T13:28:02.283698+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
2018-12-05T13:28:02.283699+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/xcodeproj-1.7.0/lib/xcodeproj/project.rb:359:in `save'
```

**Comment by segiddins** [comment]
This looks like a bug in atomos, so I’m moving the issue to that repo

**Comment by L3K0V** [comment]
Thanks @segiddins,

Can you mention me there I have update on this issue.

Workaround I found is to setup environment variable for 'TMPDIR' and it looks this issue to be related mostly to Heroku because of their file system.
