### ISSUE TITLE
NoMethodError (private method `open' called for Xcodeproj::Workspace:Class)

### ISSUE THREAD

**Issue by max-ott** [CocoaPods/Xcodeproj#730]
We recently switched to using CocoaPods and therefore are using workspaces.

Unfortunately we get an error when we want to open the `xcworkspace` file:

This is the code we are using on a Mac running macOS 10.14.16 and Xcode 11.2.1:
```
>> bundle exec irb
>> require "xcodeproj"
=> true
>> project_path = "/Users/test/app.xcworkspace"
=> "/Users/test/app.xcworkspace"
>> project = Xcodeproj::Workspace.open(project_path)
Traceback (most recent call last):
       16: from /Users/test/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load'
       15: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
       14: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
       13: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
       12: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
       11: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
       10: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
        9: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        8: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        7: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        6: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
        5: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
        4: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
        3: from /Users/test/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
        2: from /Users/test/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<top (required)>'
        1: from (irb):4
NoMethodError (private method `open' called for Xcodeproj::Workspace:Class)
```

Opening the "old" `.xcodeproj` file works without any issues. (Same location, same commands) Any help, hints or tips are highly appreciated! 🙏

**Comment by dnkoutso** [comment]
Use:
```ruby
Xcodeproj::Workspace.new_from_xcworkspace('path/to/My.xcworkspace')
```
The error message says it:
```
NoMethodError (private method `open' called for Xcodeproj::Workspace:Class)
```

Closing as I think this is just user invocation error.
