### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by songtao542** [CocoaPods/Xcodeproj#812]
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod install --ansi
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.4 (12D4e)
         Git : git version 2.6.2
Ruby lib dir : /Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ 6578f80d440113c7bb47cc5f5946bc27d31b1c11
               cocoapods - https://github.com/CocoaPods/Specs.git @ d9e2f20702c4129b79d8df830edce4c087877567
               PrivatePods - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.2
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.3.0
cocoapods-try             : 1.1.0
```

### Podfile

```ruby
# SDK 最低支持版本为 iOS 9.0 
platform :ios, '10.0'
use_frameworks!

# github 官方 pod 源
source 'https://github.com/CocoaPods/Specs.git' 

# 阿里云 pod 源
source 'https://github.com/aliyun/aliyun-specs.git' 

# 需要替换下述 "IMSDemoApp" 为开发者 App 的 target 名称 
target "smartdevice" do 
  # Pods for IMSDemoApp 
  pod 'IMSApiClient', '1.6.7'
  pod 'IMSAuthentication', '1.4.2'
  pod 'IMSIotSmart', '1.2.2'
  pod 'AlicloudSecurityGuardSDK', '5.4.165'
  pod 'AlicloudSGSecurityBody', '5.4.94'
  pod 'AlicloudSGMain', '5.4.165'
  pod 'AlicloudALBBOpenAccount', '3.4.0.47'
  pod 'AlicloudPushIoT', '1.9.5.5-noccp'
  pod 'IMSPCloudPush', '1.0.2'
  pod 'IMSPCloudNetwork', '1.0.0'
  pod 'IMSThingCapability', '1.8.9'
  pod 'IMSMobileChannel', '1.6.12'
  pod 'IMSBoneKit', '1.3.11.2'
  pod 'AKReactNative', '0.59.9.2'
  pod 'MJRefresh', '3.1.15'
  pod 'ZipArchive', '1.4.0'
  pod 'IMSReactNativeExtension', '1.0.2'
  pod 'IMSDeviceCenter', '1.12.7'
  pod 'CocoaAsyncSocket', '7.4.2'
  pod 'Reachability', '3.2'
  pod 'IMSBreezeSDK', '1.7.4'
  pod 'IMSOtaBusinessSdk', '1.6.3'
  pod 'IMSDeviceGateway', '1.6.8'
  
#  pod 'LMJDropdownMenu'
#   pod 'SnapKit', '5.0.0'

end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:218:in `initialize_from_file'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:103:in `open'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Users/developer/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/developer/Applications/CocoaPod
[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-smartdevice/Pods-smartdevice-frameworks-${CONFIGURATION}-input-files.xcfilelist"], "outputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-smartdevice/Pods-smartdevice-frameworks-${CONFIGURATION}-output-files.xcfilelist"]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-smartdevice/Pods-smartdevice-resources-${CONFIGURATION}-input-files.xcfilelist"], "outputFileListPaths"=>["${PODS_ROOT}/Target Support Files/Pods-smartdevice/Pods-smartdevice-resources-${CONFIGURATION}-output-files.xcfilelist"]} for the 'PBXShellScriptBuildPhase' isa.

**Comment by dnkoutso** [comment]
This is a very old version of xcodeproj gem and cocoapods gem. Please update both to latest versions (gem update xcodeproj and gem update cocoapods).
