### ISSUE TITLE
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:218:in `block in normalize_array_settings': undefined method `sub' for :IPHONEOS_DEPLOYMENT_TARGET:Symbol (NoMethodError) Did you mean?  succ

### ISSUE THREAD

**Issue by tomlee130** [CocoaPods/Xcodeproj#886]

**Comment by tomlee130** [comment]
% ruby build.rb                                           
'=============START============='
↓ ↓ ↓ ↓ ↓ Please Input Program's Name ↓ ↓ ↓ ↓ ↓
ssss
Traceback (most recent call last):
	17: from build.rb:9:in `<main>'
	16: from /Users/lory/myroot/source/37git/iOSTemplate/baseProj/proj_creator.rb:51:in `start'
	15: from /Users/lory/myroot/source/37git/iOSTemplate/baseProj/proj_creator.rb:132:in `save'
	14: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:364:in `save'
	13: from /Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
	11: from /Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
	10: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:365:in `block in save'
	 9: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
	 8: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:296:in `each'
	 7: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:298:in `block in to_ascii_plist'
	 6: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
	 5: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:46:in `to_hash_as'
	 4: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:46:in `tap'
	 3: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:47:in `block in to_hash_as'
	 2: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:216:in `normalize_array_settings'
	 1: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:216:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_configuration.rb:218:in `block in normalize_array_settings': undefined method `sub' for :IPHONEOS_DEPLOYMENT_TARGET:Symbol (NoMethodError)
Did you mean?  succ
