### ISSUE TITLE
while pod install show error

### ISSUE THREAD

**Issue by iamguddu1234** [CocoaPods/Xcodeproj#978]
Akshays-MacBook-Air:Demo Ads akshaybhasme$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (6.15.2)
Generating Pods project

[!] [!] Xcodeproj doesn't know about the following attributes {"fileSystemSynchronizedGroups"=>["B2BFC1A02CB91C17006FA711"]} for the 'PBXNativeTarget' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"fileSystemSynchronizedGroups"=>["B2BFC1B12CB91C19006FA711"]} for the 'PBXNativeTarget' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"fileSystemSynchronizedGroups"=>["B2BFC1BB2CB91C19006FA711"]} for the 'PBXNativeTarget' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"preferredProjectObjectVersion"=>"77"} for the 'PBXProject' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [Xcodeproj] Xcode project version (77) is higher than the latest supported by xcodeproj (63).

[!] Automatically assigning platform `iOS` with version `18.0` on target `Demo Ads` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
/Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:34:in `report'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/bin/pod:23:in `load'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/bin/pod:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:85:in `initialize': [Xcodeproj] Unable to find compatibility version string for object version `77`. (ArgumentError)
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/project.rb:48:in `initialize'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:82:in `new'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:82:in `create_project'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:73:in `generate!'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:16:in `generate!'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:320:in `block in create_and_save_projects'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:183:in `integrate'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/update.rb:63:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/bin/pod:23:in `load'
	from /Users/akshaybhasme/.gem/ruby/2.6.0/bin/pod:23:in `<main>'

**Comment by AlixH** [comment]
Up

**Comment by trickyc0d3r** [comment]
UP blyad!
