### ISSUE TITLE
`PBXProject` attempted to initialize an object with unknown ISA `PBXNativeTarget`

### ISSUE THREAD

**Issue by malavsoni** [CocoaPods/Xcodeproj#991]
### Command

```
/usr/local/bin/pod deintegrate
```

### Report

* What did you do?
- I was trying to install pods and it didn't work so I tried pod disintegrate once. 

* What did you expect to happen?
- Pods should have been deintegrated

* What happened instead?
- Facing errors maybe due to newer Xcode 16.1 version.

### Stack

```
   CocoaPods : 1.16.1
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin24]
    RubyGems : 3.0.3.1
        Host : macOS 15.1 (24B83)
       Xcode :  ()
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ ad7e9b8fa362ff6ee0132e3e45632817ac32ad24

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'TheApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheApp 
  pod 'Firebase/Core', '11.4.0'
  pod 'Firebase/Analytics', '11.4.0'
  pod 'Firebase/Crashlytics', '11.4.0'
  pod 'Firebase/Performance', '11.4.0'
  pod 'Firebase/InAppMessaging', '11.4.0'
  pod 'Firebase/Messaging', '11.4.0'
  pod 'ZIPFoundation', '0.9.19'
  pod 'RevenueCat', '5.6.0'
  pod 'SimpleKeychain', '1.2.0'
end
```

### Error

```
RuntimeError - `PBXProject` attempted to initialize an object with unknown ISA `PBXNativeTarget` from attributes: `{"isa"=>"PBXNativeTarget", "buildConfigurationList"=>"1D6058960D05DD3E006BFB54", "buildPhases"=>["8E8C4AA58583842A15571A08", "1D60588D0D05DD3D006BFB54", "1D60588E0D05DD3D006BFB54", "1D60588F0D05DD3D006BFB54", "364222430C7382ED18CF8CB9", "B60C075F2B30CE0B00A4DC21"], "buildRules"=>[], "dependencies"=>[], "fileSystemSynchronizedGroups"=>["B69122322CC5203700E775FD"], "name"=>"TheApp", "packageProductDependencies"=>["B60BA2F12B8D7E8A004E224C"], "productName"=>"OctoPod", "productReference"=>"1D6058910D05DD3D006BFB54", "productType"=>"com.apple.product-type.application"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.26.0/lib/xcodeproj/project.rb:113:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/command/deintegrate.rb:40:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.16.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.16.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by sgharraph** [comment]
I have the same issue on CircleCI while running fastlane commit_version_bump
![Screenshot 2024-11-01 at 10 49 41 AM](https://github.com/user-attachments/assets/7ce89f63-7010-4a13-9705-1232055f44b6)

I got: 
```
[18:29:55]: Called from Fastfile at line 85
[18:29:55]: ```
[18:29:55]:     83:             build_number = increment_build_number
[18:29:55]:     84:
[18:29:55]:  => 85:             commit_version_bump(
[18:29:55]:     86:                     message: "[Bump Commit] Build #{build_number}",
[18:29:55]:     87:                     xcodeproj: "****Charger.xcodeproj"
[18:29:55]: ```
[18:29:55]: `PBXProject` attempted to initialize an object with unknown ISA `PBXNativeTarget` from attributes: `{"isa"=>"PBXNativeTarget", "buildConfigurationList"=>"11DF588D26572714002E885A", "buildPhases"=>["11DF587226572714002E885A", "11DF587326572714002E885A", "11DF587426572714002E885A"], "buildRules"=>[], "dependencies"=>["11DF587826572714002E885A"], "fileSystemSynchronizedGroups"=>["EF1A65B12CBD7257009FE8D5"], "name"=>"****ChargerTests", "packageProductDependencies"=>["BD4E80E128DA6AB0009B3E0A", "BD4E80E328DA6AB0009B3E0A", "BD3572DD28DA6CAF0026B4AF", "DFD5C58D29B2A51B00B68BE2", "DFE918082C08CF470071B56F"], "productName"=>"****ChargerTests", "productReference"=>"11DF587626572714002E885A", "productType"=>"com.apple.product-type.bundle.unit-test"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

**Comment by malavsoni** [comment]
I was able to fix it by replacing the `objectVersion` to 51 from 70 in .pbxproj file;

**Comment by sgharraph** [comment]
FYI, our problem is fixed by removing fileSystemSynchronizedGroups from the .pbxproj file

**Comment by fvates-loop** [comment]
Is there no fix if I don't want to change my project file?
